# Place a copy of this config to ~/.aerospace.toml
# After that, you can edit ~/.aerospace.toml to your liking
# You can use it to add commands that run after login to macOS user session.
# 'start-at-login' needs to be 'true' for 'after-login-command' to work
# Available commands: https://nikitabobko.github.io/AeroSpace/commands©
after-login-command = []
# You can use it to add commands that run after AeroSpace startup.
# 'after-startup-command' is run after 'after-login-command'
# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = []
# Start AeroSpace at login
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# See: https://nikitabobko.github.io/AeroSpace/guide#layouts
# The 'accordion-padding' specifies the size of accordion padding
# You can set 0 to disable the padding feature
accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'horizontal'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
#on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but aæææææccidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = false 

# Possible values: (qwerty|dvorak)
# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 15
inner.vertical = 15
outer.left = 15
outer.bottom = 15
outer.top = 55
outer.right = 15


# 'main' binding mode declaration
# See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
# 'main' binding mode must be always presented
# Fallback value (if you omit the key): ‹= {}
[mode.main.binding]

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# All possible commands: https://nikitabobko.github.io/AeroSpace/commands

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec x -and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''


# See: https://nikitabobko.github.io/AeroSpace/commands#layout
ctrl-alt-cmd-w = 'layout tiling tiles horizontal vertical'     # caps-z
ctrl-alt-cmd-q = 'layout tiling accordion horizontal vertical' # caps-a
ctrl-alt-cmd-l = 'layout floating tiling'                      # caps-f

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
ctrl-alt-cmd-left = 'focus left'
ctrl-alt-cmd-down = 'focus down'
ctrl-alt-cmd-up = 'focus up'
ctrl-alt-cmd-right = 'focus right'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
ctrl-alt-cmd-shift-left = 'move left'
ctrl-alt-cmd-shift-down = 'move down'
ctrl-alt-cmd-shift-up = 'move up'
ctrl-alt-cmd-shift-right = 'move right'


# See: https://nikitabobko.github.io/AeroSpace/commands#workspacealt-shift-minus = 'resize smart -50'alt-shift-equal = 'resize smart +50'w
# See: https://nikitabobko.github.io/AeroSpace/commands#resize
ctrl-alt-cmd-1 = 'workspace 1'
ctrl-alt-cmd-2 = 'workspace 2'
ctrl-alt-cmd-3 = 'workspace 3'
ctrl-alt-cmd-4 = 'workspace 4'
ctrl-alt-cmd-5 = 'workspace 5'
ctrl-alt-cmd-6 = 'workspace 6'
ctrl-alt-cmd-o = 'workspace Mails'
ctrl-alt-cmd-t = 'workspace Terminaux'
ctrl-alt-cmd-s = 'workspace Settings'
ctrl-alt-cmd-z = 'workspace Web'       # AZERTY: ctrl-alt-cmd-w
ctrl-alt-cmd-f = 'workspace Files'
ctrl-alt-cmd-c = 'workspace Code'
ctrl-alt-cmd-y = 'workspace Music'
ctrl-alt-cmd-x = 'workspace XCode'
ctrl-alt-cmd-d = 'workspace Dev'


ctrl-alt-cmd-period = 'balance-sizes' # caps-b
# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
ctrl-alt-cmd-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
ctrl-alt-cmd-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
ctrl-alt-cmd-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
ctrl-alt-cmd-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
ctrl-alt-cmd-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
ctrl-alt-cmd-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
ctrl-alt-cmd-shift-o = ['move-node-to-workspace Mails', 'workspace Mails']
ctrl-alt-cmd-shift-t = [
    'move-node-to-workspace Terminaux',
    'workspace Terminaux',
]
ctrl-alt-cmd-shift-s = ['move-node-to-workspace Settings', 'workspace Settings']
ctrl-alt-cmd-shift-z = [
    'move-node-to-workspace Web',
    'workspace Web',
] # AZERTY: ctrl-alt-cmd-shift-w
ctrl-alt-cmd-shift-f = ['move-node-to-workspace Files', 'workspace Files']
ctrl-alt-cmd-shift-c = ['move-node-to-workspace Code', 'workspace Code']
ctrl-alt-cmd-shift-y = ['move-node-to-workspace Music', 'workspace Music']
ctrl-alt-cmd-shift-x = ['move-node-to-workspace XCode', 'workspace XCode']
ctrl-alt-cmd-shift-d = ['move-node-to-workspace Dev', 'workspace Dev']

ctrl-alt-cmd-f11 = 'move-workspace-to-monitor --wrap-around prev'
ctrl-alt-cmd-f12 = 'move-workspace-to-monitor --wrap-around next'

ctrl-alt-cmd-u = 'fullscreen --no-outer-gaps'

ctrl-alt-cmd-m = 'resize smart -200'          # ,
ctrl-alt-cmd-comma = 'resize smart +200'      # ;
ctrl-alt-cmd-shift-m = 'resize smart -50'     # ;
ctrl-alt-cmd-shift-comma = 'resize smart +50' # :

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
ctrl-alt-cmd-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitorcxx
ctrl-alt-cmd-shift-tab = 'move-workspace-to-monitor --wrap-around next'

#ctrl-alt-cmd-r = 'flatten-workspace-tree'                # reset layoutb
ctrl-alt-cmd-backspace = 'close-all-windows-but-current'


# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

#ctrl-alt-cmd-h = ['join-with zleft']
#ctrl-alt-cmd-j = ['join-with down']
#ctrl-alt-cmd-k = ['join-with up']
#ctrl-alt-cmd-l = ['join-with right']
[[on-window-detected]]
check-further-callbacks = true
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.mozilla.nightly'
run = ['layout tiling', 'move-node-to-workspace Web']

[[on-window-detected]]
if.app-id = 'org.mozilla.nightly'
if.window-title-regex-substring = 'Picture-in-Picture'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = ['layout tiling', 'move-node-to-workspace Music']

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = ['layout tiling', 'move-node-to-workspace Code']

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = ['move-node-to-workspace Mails']

[[on-window-detected]]
if.app-id = 'com.microsoft.teams2'
run = ['layout tiling', 'move-node-to-workspace Terminaux']

[[on-window-detected]]
if.app-id = 'org.yanex.marta'
run = ['layout tiling', 'move-node-to-workspace Files']

[[on-window-detected]]
if.app-id = 'com.apple.AppStore'
run = ['layout tiling', 'move-node-to-workspace Settings']

[[on-window-detected]]
if.app-id = 'com.apple.systempreferences'
run = ['move-node-to-workspace Settings']

[[on-window-detected]]
if.app-id = 'com.apple.dt.Xcode'
run = ['move-node-to-workspace XCode']

[[on-window-detected]]
if.app-id = 'com.DanPristupov.Fork'
run = ['layout tiling', 'move-node-to-workspace Dev']

[workspace-to-monitor-force-assignment]
Code = 1
XCode = 2
Web = 3
Dev = 3
