#!/usr/bin/env zsh

# load scripting additions
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Start Yabai at login
launchctl load -w ~/Library/LaunchAgents/com.yabai.plist

#
# setup spaces
#
for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 7)'); do
  yabai -m space --destroy 7
done

function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}


setup_space 1 web
setup_space 2 outlook
setup_space 3 dev
setup_space 4 media
setup_space 5 terminal
setup_space 6 rand1


# default latout
yabai -m config layout bsp

# Gaps Configuration
yabai -m config top_padding    15
yabai -m config bottom_padding 15
yabai -m config left_padding   15
yabai -m config right_padding  15
yabai -m config window_gap     15
yabai -m config external_bar all:40:0
yabai -m config window_placement second_child

# Window conf
yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai  -m config normal_window_opacity 1
yabai -m config normal_window_opacity 0.9
yabai -m config window_opacity_duration 0.05
yabai -m config window_animation_duration 0.1
yabai -m config window_animation_easing ease_out_quint
# Application Rules                     

## iTerm Hotkey Window always floating
yabai -m rule --add app="iTerm2" title=".*Hotkey Window.*" manage=off

yabai -m config insert_feedback_color 0xfff6ba22


# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|VirtualBuddy|iTerm2|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|Raycast|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|scurity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off


# move some apps automatically to specific spaces
yabai -m rule space=^6
yabai -m rule --add app="^Safari$" space=^1
yabai -m rule --add app="^Firefox Nightly$" space=^1
yabai -m rule --add app="^Outlook$" space=^2
yabai -m rule --add app="^Teams$" space=^2
yabai -m rule --add app="^Code$" space=^3cw
yabai -m rule --add app="^Music$" space=^4
yabai -m rule --add app="^Spotify$" space=^4
yabai -m rule --add app="^kitty$" space=^5

yabai -m config debug_output on