#!/usr/bin/env zsh

# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# .. more yabai startup stuff


# Yabai General Configuration
# yabai -m config mouse_follows_focus          on
# yabai -m config focus_follows_mouse          autofocus


# Start Yabai at login
launchctl load -w ~/Library/LaunchAgents/com.yabai.plist

# Gaps Configuration
yabai -m config top_padding    15
yabai -m config bottom_padding 15
yabai -m config left_padding   15
yabai -m config right_padding  15
yabai -m config window_gap     15
yabai -m config external_bar all:40:0
yabai -m config window_placement second_child

# Window conf
yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off
yabai -m config window_opacity on
yabai -m config normal_window_opacity 1
yabai -m config normal_window_opacity 0.9
yabai -m config window_opacity_duration 0.05
yabai -m config window_animation_duration 0.1
yabai -m config window_animation_easing ease_out_quint
# Application Rules

## iTerm Hotkey Window always floating
yabai -m rule --add app="iTerm2" title=".*Hotkey Window.*" manage=off

yabai -m config insert_feedback_color 0xfff6ba22


# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Raycast|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off


# Default layout Configuration
yabai -m config layout bsp